# Generated by Django 2.2 on 2019-06-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('default', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(blank=True, limit_choices_to={'active': True}, null=True, to='products.Product')),
            ],
        ),
    ]
